### ISSUE TITLE
Проблема с Kint-Twig

### ISSUE THREAD

**Issue by wierdo3432** [regiomedia/bitrix-project#14]
При ициниализации нового проекта получил такую ошибку в файле event.php

**[Error] 
Class 'Kint_TwigExtension' not found (0)** 

хотя kint-twig в vendor присутствует

![2018-12-17 19 56 48](https://user-images.githubusercontent.com/45946715/50102377-f9dc5700-0235-11e9-83a7-d14d57e3714b.png)

**Comment by vkryukov76** [comment]
Совершенно точно помню, что такая проблема возникала, но вот как ее решали, вспомнить не могу 🤔

**Comment by greal** [comment]
@wierdo3432 Все просто, обновился namespace, в local/php_interface/events.php добавить:

```
use Kint\Twig\TwigExtension;
```

И изменить на это:

```
$engine->addExtension(new TwigExtension());
```
